version: '3.7'
services:
    camp-lake-api:
        container_name: camp-lake-api
        environment:
            GOPATH: /go/
            API_PORT: 20001
            MONGO_HOST: mongodb
            MONGO_DATABASE_NAME: DB
            MONGO_PORT: 27017
            MONGO_TIMEOUT: 60
            MONGO_PORT: 27017
            MONGO_TIMEOUT: 60
        env_file:
            - dockers.env
        build:
            context: ../
            dockerfile: deployments/api.Dockerfile
        command: "go run server.go"
        volumes:
            - docker_vol:/var/lib/docker
        ports:
          - "20001:20001"
        networks:
            - a1_net
        depends_on:
            - mongodb

    mongodb:
        container_name: mongodb
        build:
            context: ../
            dockerfile: deployments/mongo.Dockerfile
        ports:
          - "27017:27017"
          - "27018:27018"
        volumes:
            - mongo_vol:/data/db
        networks:
            - a1_net
networks:
    a1_net:

volumes:
    docker_vol:
    mongo_vol: