version: "3"
services:
  app:
    platform: linux/x86_64
    container_name: app-a6
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    ports:
      - "10006:10006"
    restart: always
